import type { Agent, Conversation } from "@/types/chat";

export const mockAgents: Agent[] = [
  { id: "agt-001", name: "Nguyễn Thị Lan", avatar: undefined, status: "online", activeChats: 3 },
  { id: "agt-002", name: "Trần Văn Minh", avatar: undefined, status: "online", activeChats: 2 },
  { id: "agt-003", name: "Lê Hoàng Nam", avatar: undefined, status: "busy", activeChats: 5 },
  { id: "agt-004", name: "Phạm Thị Oanh", avatar: undefined, status: "offline", activeChats: 0 },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-001",
    customerId: "usr-101",
    customerName: "Nguyễn Văn An",
    customerEmail: "an.nguyen@email.com",
    agentId: "agt-001",
    agentName: "Nguyễn Thị Lan",
    status: "in_progress",
    subject: "Đơn hàng #1234 chưa nhận được",
    lastMessage: "Chúng tôi đang kiểm tra với đơn vị vận chuyển",
    messages: [
      { id: "msg-001", conversationId: "conv-001", senderId: "usr-101", senderName: "Nguyễn Văn An", senderType: "customer", content: "Tôi đặt hàng 5 ngày trước nhưng chưa nhận được", createdAt: "2026-03-23T09:00:00Z" },
      { id: "msg-002", conversationId: "conv-001", senderId: "bot", senderName: "Bot", senderType: "bot", content: "Xin chào! Cảm ơn bạn đã liên hệ. Tôi sẽ chuyển bạn đến nhân viên hỗ trợ.", createdAt: "2026-03-23T09:00:30Z" },
      { id: "msg-003", conversationId: "conv-001", senderId: "agt-001", senderName: "Nguyễn Thị Lan", senderType: "agent", content: "Chào anh An, tôi sẽ kiểm tra đơn hàng #1234 ngay ạ", createdAt: "2026-03-23T09:02:00Z" },
      { id: "msg-004", conversationId: "conv-001", senderId: "agt-001", senderName: "Nguyễn Thị Lan", senderType: "agent", content: "Chúng tôi đang kiểm tra với đơn vị vận chuyển", createdAt: "2026-03-23T09:05:00Z" },
    ],
    createdAt: "2026-03-23T09:00:00Z",
    updatedAt: "2026-03-23T09:05:00Z",
  },
  {
    id: "conv-002",
    customerId: "usr-102",
    customerName: "Trần Thị Bình",
    customerEmail: "binh.tran@email.com",
    agentId: "agt-002",
    agentName: "Trần Văn Minh",
    status: "assigned",
    subject: "Hỏi về chính sách đổi trả",
    lastMessage: "Tôi muốn đổi size áo đã mua tuần trước",
    messages: [
      { id: "msg-005", conversationId: "conv-002", senderId: "usr-102", senderName: "Trần Thị Bình", senderType: "customer", content: "Tôi muốn đổi size áo đã mua tuần trước", createdAt: "2026-03-23T10:00:00Z" },
    ],
    createdAt: "2026-03-23T10:00:00Z",
    updatedAt: "2026-03-23T10:00:00Z",
  },
  {
    id: "conv-003",
    customerId: "usr-103",
    customerName: "Lê Minh Châu",
    customerEmail: "chau.le@email.com",
    status: "open",
    subject: "Sản phẩm bị lỗi",
    lastMessage: "Sản phẩm tôi nhận được bị hỏng",
    messages: [
      { id: "msg-006", conversationId: "conv-003", senderId: "usr-103", senderName: "Lê Minh Châu", senderType: "customer", content: "Sản phẩm tôi nhận được bị hỏng, tôi cần được hỗ trợ", createdAt: "2026-03-23T11:00:00Z" },
    ],
    createdAt: "2026-03-23T11:00:00Z",
    updatedAt: "2026-03-23T11:00:00Z",
  },
  {
    id: "conv-004",
    customerId: "usr-104",
    customerName: "Phạm Đức Dũng",
    customerEmail: "dung.pham@email.com",
    agentId: "agt-001",
    agentName: "Nguyễn Thị Lan",
    status: "resolved",
    subject: "Hoàn tiền đơn hàng #1100",
    lastMessage: "Cảm ơn bạn, tiền đã được hoàn lại",
    messages: [
      { id: "msg-007", conversationId: "conv-004", senderId: "usr-104", senderName: "Phạm Đức Dũng", senderType: "customer", content: "Tôi muốn hoàn tiền đơn hàng #1100", createdAt: "2026-03-22T14:00:00Z" },
      { id: "msg-008", conversationId: "conv-004", senderId: "agt-001", senderName: "Nguyễn Thị Lan", senderType: "agent", content: "Chào anh Dũng, tôi đã xử lý hoàn tiền cho đơn hàng #1100", createdAt: "2026-03-22T14:30:00Z" },
      { id: "msg-009", conversationId: "conv-004", senderId: "usr-104", senderName: "Phạm Đức Dũng", senderType: "customer", content: "Cảm ơn bạn, tiền đã được hoàn lại", createdAt: "2026-03-22T15:00:00Z" },
    ],
    createdAt: "2026-03-22T14:00:00Z",
    updatedAt: "2026-03-22T15:00:00Z",
  },
  {
    id: "conv-005",
    customerId: "usr-105",
    customerName: "Hoàng Thị Em",
    customerEmail: "em.hoang@email.com",
    agentId: "agt-003",
    agentName: "Lê Hoàng Nam",
    status: "closed",
    subject: "Hỏi mã giảm giá",
    lastMessage: "Cảm ơn bạn!",
    messages: [
      { id: "msg-010", conversationId: "conv-005", senderId: "usr-105", senderName: "Hoàng Thị Em", senderType: "customer", content: "Mã giảm giá SALE30 có còn hiệu lực không?", createdAt: "2026-03-21T08:00:00Z" },
      { id: "msg-011", conversationId: "conv-005", senderId: "agt-003", senderName: "Lê Hoàng Nam", senderType: "agent", content: "Chào chị Em, mã SALE30 giảm 30% áp dụng đến hết 31/03", createdAt: "2026-03-21T08:05:00Z" },
      { id: "msg-012", conversationId: "conv-005", senderId: "usr-105", senderName: "Hoàng Thị Em", senderType: "customer", content: "Cảm ơn bạn!", createdAt: "2026-03-21T08:06:00Z" },
    ],
    createdAt: "2026-03-21T08:00:00Z",
    updatedAt: "2026-03-21T08:06:00Z",
  },
];
