import type { Survey, SurveyResponse } from "@/types/survey";

export const mockSurveys: Survey[] = [
  {
    id: "srv-001",
    type: "NPS",
    title: "Khảo sát NPS sau mua hàng",
    description: "Đo lường mức độ giới thiệu sau khi hoàn tất đơn hàng",
    questions: [
      { id: "q1", text: "Bạn có sẵn sàng giới thiệu chúng tôi cho bạn bè?", type: "rating", required: true },
      { id: "q2", text: "Lý do cho điểm số trên?", type: "text", required: false },
    ],
    triggerPoint: "post_purchase",
    active: true,
    responseCount: 342,
    averageScore: 8.4,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-03-20T10:30:00Z",
  },
  {
    id: "srv-002",
    type: "CSAT",
    title: "Đánh giá hỗ trợ khách hàng",
    description: "Khảo sát sau khi đóng ticket hỗ trợ",
    questions: [
      { id: "q1", text: "Bạn hài lòng với dịch vụ hỗ trợ?", type: "rating", required: true },
      { id: "q2", text: "Nhân viên hỗ trợ có thân thiện không?", type: "single_choice", options: ["Rất thân thiện", "Bình thường", "Không thân thiện"], required: true },
    ],
    triggerPoint: "ticket_closed",
    active: true,
    responseCount: 189,
    averageScore: 4.2,
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-18T14:00:00Z",
  },
  {
    id: "srv-003",
    type: "CES",
    title: "Đánh giá trải nghiệm thanh toán",
    description: "Mức độ dễ dàng khi thanh toán đơn hàng",
    questions: [
      { id: "q1", text: "Quá trình thanh toán có dễ dàng không?", type: "rating", required: true },
    ],
    triggerPoint: "checkout_complete",
    active: true,
    responseCount: 567,
    averageScore: 4.5,
    createdAt: "2026-01-20T07:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "srv-004",
    type: "NPS",
    title: "Khảo sát NPS định kỳ Q1",
    description: "Khảo sát hàng quý gửi cho khách hàng trung thành",
    questions: [
      { id: "q1", text: "Bạn có sẵn sàng giới thiệu chúng tôi?", type: "rating", required: true },
      { id: "q2", text: "Điều gì chúng tôi có thể cải thiện?", type: "text", required: false },
    ],
    triggerPoint: "quarterly",
    active: false,
    responseCount: 1203,
    averageScore: 7.8,
    createdAt: "2025-12-01T08:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "srv-005",
    type: "CSAT",
    title: "Đánh giá sản phẩm mới",
    description: "Thu thập phản hồi về bộ sưu tập mới ra mắt",
    questions: [
      { id: "q1", text: "Bạn đánh giá sản phẩm mới thế nào?", type: "rating", required: true },
      { id: "q2", text: "Bạn thích điều gì nhất?", type: "multiple_choice", options: ["Chất lượng", "Giá cả", "Thiết kế", "Đóng gói"], required: false },
    ],
    triggerPoint: "product_delivery",
    active: true,
    responseCount: 95,
    averageScore: 4.6,
    createdAt: "2026-03-10T08:00:00Z",
    updatedAt: "2026-03-23T16:00:00Z",
  },
];

export const mockSurveyResponses: SurveyResponse[] = [
  { id: "res-001", surveyId: "srv-001", userId: "usr-101", customerName: "Nguyễn Văn An", score: 9, comment: "Dịch vụ rất tốt, giao hàng nhanh", answers: { q1: 9, q2: "Dịch vụ rất tốt" }, createdAt: "2026-03-20T14:30:00Z" },
  { id: "res-002", surveyId: "srv-001", userId: "usr-102", customerName: "Trần Thị Bình", score: 7, comment: "Sản phẩm ổn nhưng giao hàng hơi chậm", answers: { q1: 7, q2: "Giao hàng chậm" }, createdAt: "2026-03-20T15:00:00Z" },
  { id: "res-003", surveyId: "srv-002", userId: "usr-103", customerName: "Lê Minh Châu", score: 5, comment: "Nhân viên hỗ trợ rất nhiệt tình", answers: { q1: 5, q2: "Rất thân thiện" }, createdAt: "2026-03-19T10:00:00Z" },
  { id: "res-004", surveyId: "srv-003", userId: "usr-104", customerName: "Phạm Đức Dũng", score: 4, answers: { q1: 4 }, createdAt: "2026-03-22T08:30:00Z" },
  { id: "res-005", surveyId: "srv-001", userId: "usr-105", customerName: "Hoàng Thị Em", score: 10, comment: "Tuyệt vời! Sẽ giới thiệu cho bạn bè", answers: { q1: 10, q2: "Tuyệt vời" }, createdAt: "2026-03-21T09:00:00Z" },
  { id: "res-006", surveyId: "srv-002", userId: "usr-106", customerName: "Võ Văn Phúc", score: 3, comment: "Phải chờ đợi lâu", answers: { q1: 3, q2: "Bình thường" }, createdAt: "2026-03-18T16:00:00Z" },
  { id: "res-007", surveyId: "srv-003", userId: "usr-107", customerName: "Đỗ Thị Giang", score: 5, comment: "Thanh toán nhanh gọn", answers: { q1: 5 }, createdAt: "2026-03-22T11:00:00Z" },
  { id: "res-008", surveyId: "srv-005", userId: "usr-108", customerName: "Bùi Hữu Hải", score: 4, answers: { q1: 4, q2: "Thiết kế" }, createdAt: "2026-03-23T14:00:00Z" },
  { id: "res-009", surveyId: "srv-001", userId: "usr-109", customerName: "Ngô Thị Inh", score: 6, comment: "Bình thường", answers: { q1: 6, q2: "Bình thường" }, createdAt: "2026-03-20T17:00:00Z" },
  { id: "res-010", surveyId: "srv-004", userId: "usr-110", customerName: "Lý Văn Khánh", score: 8, comment: "Dịch vụ ngày càng tốt hơn", answers: { q1: 8, q2: "Cải thiện giao hàng" }, createdAt: "2026-02-28T10:00:00Z" },
];
